# Generated by Django 5.1.4 on 2024-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="voice_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
