# Generated by Django 5.1.4 on 2024-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_app", "0002_alter_agent_voice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="voice_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
